"kiss pick" function added

diff --git a/kiss b/kiss
--- a/kiss
+++ b/kiss
@@ -68,7 +68,7 @@ run() {
 # but which function has an output.
 # This delegation makes it sure of only getting the printf content after the last \n,
 # which content comes from a
-# printf "\n%s" "$output"
+# function_name() { printf "\n%s" "$output"; }
 # local var="$(delegate "function_name" "$@")"
 delegate() {
     log "$FUNCNAME" '$@' "$(esceval "$FUNCNAME" "$@")"
@@ -103,22 +103,12 @@ standardize() {
         [ "$(expr substr $path $src_length 1)" = '/' ] && {
             path="$(expr substr $path 1 $((src_length - 1)) )"
         }
-    }
-    [ "$path" != "$1" ] && path="$(standardize "$path")"
-    printf "%s" "$path"
-}
-
-# TODO #{var%%\*}
-# Should be subshell function
-std_exec() {
-    local path="$1"
-    ok "$path" && {
-        local src_length=${#path}
+        src_length=${#path}
         [ "$(expr substr $path $src_length 1)" = '*' ] && {
             path="$(expr substr $path 1 $((src_length - 1)) )"
         }
     }
-    [ "$path" != "$1" ] && path="$(std_exec "$path")"
+    [ "$path" != "$1" ] && path="$(standardize "$path")"
     printf "%s" "$path"
 }
 
@@ -377,6 +367,7 @@ slot_aquire() {
 }
 
 # Copy an extarnal file to temporary directory in one time
+# Won't create empty file
 # $1 scope        : function name
 # $2 src_address  : source file full path
 slot_push() {
@@ -606,13 +597,6 @@ pkg_version() {
     local shell_flag="$3"
     local search_path="$4"
 
-    # case "$repo_dir" in
-    #     *"${REPO_MAIN}"*)
-    #         sed -i 's:#!/bin/sh -e:#!/usr/bin/env sh:g' "$repo_dir/build"
-    #         ;;
-    #     *) :;;
-    # esac
-
     ver_pre=$repo_ver
     rel_pre=$repo_rel
 
@@ -620,7 +604,7 @@ pkg_version() {
     if [ -d "$repo_dir" ]; then
         debug "$FUNCNAME" '$repo_dir' "$repo_dir"
     else
-        die "$FUNCNAME" "$pkg" "Failed to read directory ($repo_dir)"
+        die "$FUNCNAME" '$repo_dir' "No such package ($pkg)"
     fi
 
     IFS=$"(printf ' ')" read -r repo_ver repo_rel 2>/dev/null < "$repo_dir/version" ||
@@ -668,6 +652,54 @@ pkg_version_split() {
 
 }
 
+# Query package from /var/db/kiss without being limited by $KISS_PATH
+# and install it from the query index (optional)
+# $1 target
+# $2 index: selected one
+pick_up() {
+    local index=0
+    local target="${1}"
+    local selected=
+    local ver_selected=
+    local sub_ver_selected=
+    local packages="$(find "/var/db/kiss" \( -type d -o -type l \) -name "${target}")"
+    for pack in $packages
+    do
+        [ -d "$pack" ] && [ -f "$pack/version" ] && {
+            read -r ver sub_ver 2>/dev/null < "$pack/version" || {
+                printf "%s\n" "Failed to read version file ($pack/version)"
+                exit 1
+            }
+            printf "%-4d %-9s %-4s %s\n" $((index)) "$ver" "$sub_ver" "$pack"
+            if [ -n "$2" ] && [ $index = $2 ]; then
+                selected="$pack"
+                ver_selected="$ver"
+                sub_ver_selected="$sub_ver"
+            fi
+            index=$(($index + 1))
+        }
+    done
+    if [ -n "$selected" ]; then
+        printf "\n%s\n%-4d %-9s %-4s %s\n\n" "Selected package:" $2  "$ver_selected" "$sub_ver_selected" "$selected"
+        local dir="$(dirname "$selected")"
+        local base="$(basename "$selected")"
+        if [ -z "${USE_GMAKE}" ]; then
+            printf "\n%s\n\n" "BSD make used"
+        else
+            printf "\n%s\n\n" "GNU make used"
+            local build_root="${HOME}/.cache/kiss/proc/$base"
+            [ ! -d "${build_root}/bin" ] && mkdir -p "${build_root}/bin"
+            [ "$(readlink "${build_root}/bin/gunzip")" != "/usr/bin/pigz"  ] && \ln -sf "/usr/bin/pigz"  "${build_root}/bin/gunzip"
+            [ "$(readlink "${build_root}/bin/make")"   != "/usr/bin/gmake" ] && \ln -sf "/usr/bin/gmake" "${build_root}/bin/make"
+            export PATH="${build_root}/bin:$PATH"
+        fi
+        export KISS_PATH=$dir
+        /usr/bin/kiss c $base 2>&1 > /dev/stderr &&
+        /usr/bin/kiss b $base 2>&1 > /dev/stderr &&
+        /usr/bin/kiss i $base
+    fi
+}
+
 # # $1 pkg
 # # $2 option: "all" for executable and "" for repository
 # # $4 -d or -x
@@ -700,8 +732,7 @@ pkg_find() {
     # directories matching the package name in $KISS_PATH/*.
     set -- "$1" "$2" "$3" "${4:-"$KISS_PATH"}"
     local pkg="$1"
-    pkg="$(std_exec "$pkg")"
-    pkg=${pkg%%\*}
+    pkg="$(standardize "$pkg")" # pkg=${pkg%%\*}
     local select="$2"
     debug "$FUNCNAME " '$pkg' "$pkg [local]"
     local pkg_name="${pkg##*/}"
@@ -981,6 +1012,7 @@ pkg_source() {
     log "$FUNCNAME" "$pkg_name" "Reading sources"
 
     while read -r src dest || ok "$src"; do
+        [ "$src" != '#' ] || continue
         log "$FUNCNAME" '$src'  "$src"
         log "$FUNCNAME" '$dest' "$dest"
         IFS=$'\3' read -r _res _des < <(pkg_source_resolve "$pkg_name" "$src" "$dest" "$action")
@@ -1142,7 +1174,7 @@ pkg_extract() {
         IFS=$'\3' read -r _res _des < <(pkg_source_resolve "$pkg_name" "$src" "$dest") > /dev/null
 
         # Create the source's directories if not null.
-        null "$_res" || mkcd "$FUNCNAME" "$mak_dir/$dest"
+        null "$_res" || mkcd "$FUNCNAME" "$(standardize "$mak_dir/$dest")"
 
         case $_res in
             git+*)
@@ -1830,6 +1862,7 @@ pkg_build() {
         RUSTFLAGS="--remap-path-prefix=$PWD=. $RUSTFLAGS" \
         GOFLAGS="-trimpath -modcacherw $GOFLAGS" \
         GOPATH="$PWD/go" \
+        PATH="$GOPATH/bin:$PATH" \
         KISS_ROOT="$KISS_ROOT" \
         \
         "$repo_dir/build" "$pkg_dir" "$repo_ver" 2>&1 || {
@@ -2279,12 +2312,15 @@ pkg_remove() {
     run_hook     pre-remove "$pkg" "$sys_db/$pkg"
 
     log "$FUNCNAME" '$pkg' "$pkg"
-    # Make a backup of any etcsums if they exist.
-    local etcsums_clone="$(delegate "slot_push" "$FUNCNAME" "$sys_db/$pkg/etcsums")"
-
     log "$FUNCNAME" "removing package" "$pkg"
-    [ -f "$sys_db/$pkg/manifest" ] && pkg_remove_files < "$sys_db/$pkg/manifest" 3< "$etcsums_clone"
-
+    # Make a backup of any etcsums if they exist.
+    [ -f "$sys_db/$pkg/manifest" ] && {
+        [ ! -s "$sys_db/$pkg/etcsums" ] &&
+        pkg_remove_files < "$sys_db/$pkg/manifest" || {
+            local etcsums_clone="$(delegate "slot_push" "$FUNCNAME" "$sys_db/$pkg/etcsums")"
+            pkg_remove_files < "$sys_db/$pkg/manifest" 3< "$etcsums_clone"
+        }
+    }
     # Reset 'trap' to its original value. Removal is done so
     # we no longer need to block 'Ctrl+C'.
     trap pkg_clean EXIT INT
@@ -2931,7 +2967,6 @@ tmp_dirs() {
     # printf "%s" "$pkg_root"
 }
 
-# TODO depends on PPID not correct in sub process
 tmp_clean() {
     set -efE
     trap 'Error in function $FUNCNAME at line $LINENO' ERR
@@ -3061,6 +3096,7 @@ args() {
         H|help-ext)     pkg_help_ext "$@" ;;
         i|install)      for pkg do tmp_dirs "$pkg"; pkg_install "$pkg"; done ;;
         l|list)         pkg_list_version "$FUNCNAME" "$@" ;;
+        p|pick)         pick_up "$1" "$2" ;;
         r|remove)       for pkg in $redro; do pkg_remove "$pkg"; done ;;
         s|search)       for pkg do for item in $(delegate "pkg_find" "$pkg" all); do log "$pkg" "$item"; done; done ;;
         u|update)       pkg_update ;;
@@ -3075,6 +3111,7 @@ args() {
             log "$FUNCNAME" 'download' 'Download sources'
             log "$FUNCNAME" 'install'  'Install packages'
             log "$FUNCNAME" 'list'     'List installed packages'
+            log "$FUNCNAME" 'pick'     'Query and pick up package'
             log "$FUNCNAME" 'remove'   'Remove packages'
             log "$FUNCNAME" 'search'   'Search for packages'
             log "$FUNCNAME" 'update'   'Update the system and repositories'
